import { analyze } from "./analysis";
import { parseCsv, toTable } from "./csv";
import { resolveColumns } from "./columns";
import { extractAds } from "./extract";
import { generateMemo } from "./memo";
import { DebriefContext, Memo } from "./types";

/**
 * The sample report is generated by the REAL engine from this
 * hardcoded, realistic dataset — the same code path as an upload, so
 * what a first-timer sees is exactly what they'll get, not marketing
 * copy. Everything is deterministic, so this renders server-side.
 *
 * The dataset is designed to exercise the interesting paths: a clear
 * winner group, a kill list, two ads below the spend gate (including
 * one with a great ROAS on tiny spend — the honesty case), and ad
 * names that carry a format signal (UGC vs static vs video).
 */
const SAMPLE_CSV = `Ad name,Amount spent (USD),Purchases,Purchase ROAS (return on ad spend),Reporting starts,Reporting ends
UGC — Ana testimonial 15s,412.55,31,4.82,2026-06-01,2026-06-30
UGC — Marta routine POV,388.10,27,4.31,2026-06-01,2026-06-30
Video — 15s demo hook v2,344.20,22,3.65,2026-06-01,2026-06-30
Video — Before/after glow,296.40,17,3.10,2026-06-01,2026-06-30
Static — Ingredient callout,251.75,12,2.68,2026-06-01,2026-06-30
Static — Product on marble,240.00,10,2.41,2026-06-01,2026-06-30
UGC — Duo reaction clip,233.30,9,2.24,2026-06-01,2026-06-30
Static — Discount banner 25%,228.65,8,1.95,2026-06-01,2026-06-30
Static — Lifestyle flatlay,214.80,7,1.71,2026-06-01,2026-06-30
Video — Founder story 30s,205.90,5,1.42,2026-06-01,2026-06-30
Static — Press quote card,82.40,3,2.05,2026-06-01,2026-06-30
UGC — Whitelisted creator test,44.95,2,5.40,2026-06-01,2026-06-30`;

export const SAMPLE_CONTEXT: DebriefContext = {
  kpi: "roas",
  product: "Lumen Skincare — Vitamin C Serum",
  offer: "25% off first order",
  goal: "Scale past $500/day profitably",
  targetCpa: null,
  creativeNotes:
    "UGC ads are creator testimonials; statics are product-on-marble shots; videos are 15s demo hooks.",
};

export function buildSampleMemo(): Memo {
  const matrix = parseCsv(SAMPLE_CSV);
  const { headers, rows } = toTable(matrix);
  const columns = resolveColumns(headers);
  const ads = extractAds(rows, columns, SAMPLE_CONTEXT.kpi);
  const analysis = analyze(ads, rows, columns, SAMPLE_CONTEXT);
  return generateMemo(analysis, SAMPLE_CONTEXT);
}
