import { analyze } from "./analysis";
import { parseCsv, toTable } from "./csv";
import { resolveColumns } from "./columns";
import { extractAds } from "./extract";
import { generateMemo } from "./memo";
import { Memo } from "./types";
import { SAMPLE_CONTEXT, SAMPLE_CSV_TEXT } from "./sampleCsv";

/**
 * The sample report is generated by the REAL engine from the shared
 * synthetic dataset (sampleCsv.ts — same data the generator's "Use
 * sample data" button loads), the same code path as an upload, so what
 * a first-timer sees is exactly what they'll get, not marketing copy.
 * Everything is deterministic, so this renders server-side.
 */
export function buildSampleMemo(): Memo {
  const matrix = parseCsv(SAMPLE_CSV_TEXT);
  const { headers, rows } = toTable(matrix);
  const columns = resolveColumns(headers);
  const ads = extractAds(rows, columns, SAMPLE_CONTEXT.kpi);
  const analysis = analyze(ads, rows, columns, SAMPLE_CONTEXT);
  return generateMemo(analysis, SAMPLE_CONTEXT);
}
